export interface IIcons {
  decoration_1: string
  attack: string
  defense: string
  affinity: string
  villager: string
  bones: string
  element_fire: string
  element_ice: string
  element_water: string
  element_thunder: string
  element_dragon: string
  element_sleep: string
  element_poison: string
  element_paralisys: string
  element_blast: string
  head_1: string
  head_2: string
  head_3: string
  head_4: string
  head_5: string
  head_6: string
  head_7: string
  head_8: string
  head_9: string
  head_10: string
  chest_1: string
  chest_2: string
  chest_3: string
  chest_4: string
  chest_5: string
  chest_6: string
  chest_7: string
  chest_8: string
  chest_9: string
  chest_10: string
  waist_1: string
  waist_2: string
  waist_3: string
  waist_4: string
  waist_5: string
  waist_6: string
  waist_7: string
  waist_8: string
  waist_9: string
  waist_10: string
  arms_1: string
  arms_2: string
  arms_3: string
  arms_4: string
  arms_5: string
  arms_6: string
  arms_7: string
  arms_8: string
  arms_9: string
  arms_10: string
  legs_1: string
  legs_2: string
  legs_3: string
  legs_4: string
  legs_5: string
  legs_6: string
  legs_7: string
  legs_8: string
  legs_9: string
  legs_10: string
  bow_1: string
  bow_2: string
  bow_3: string
  bow_4: string
  bow_5: string
  bow_6: string
  bow_7: string
  bow_8: string
  bow_9: string
  bow_10: string
  light_bow_gun_1: string
  light_bow_gun_2: string
  light_bow_gun_3: string
  light_bow_gun_4: string
  light_bow_gun_5: string
  light_bow_gun_6: string
  light_bow_gun_7: string
  light_bow_gun_8: string
  light_bow_gun_9: string
  light_bow_gun_10: string
  charge_blade_1: string
  charge_blade_2: string
  charge_blade_3: string
  charge_blade_4: string
  charge_blade_5: string
  charge_blade_6: string
  charge_blade_7: string
  charge_blade_8: string
  charge_blade_9: string
  charge_blade_10: string
  dual_blades_1: string
  dual_blades_2: string
  dual_blades_3: string
  dual_blades_4: string
  dual_blades_5: string
  dual_blades_6: string
  dual_blades_7: string
  dual_blades_8: string
  dual_blades_9: string
  dual_blades_10: string
  great_sword_1: string
  great_sword_2: string
  great_sword_3: string
  great_sword_4: string
  great_sword_5: string
  great_sword_6: string
  great_sword_7: string
  great_sword_8: string
  great_sword_9: string
  great_sword_10: string
  hammer_1: string
  hammer_2: string
  hammer_3: string
  hammer_4: string
  hammer_5: string
  hammer_6: string
  hammer_7: string
  hammer_8: string
  hammer_9: string
  hammer_10: string
  heavy_bow_gun_1: string
  heavy_bow_gun_2: string
  heavy_bow_gun_3: string
  heavy_bow_gun_4: string
  heavy_bow_gun_5: string
  heavy_bow_gun_6: string
  heavy_bow_gun_7: string
  heavy_bow_gun_8: string
  heavy_bow_gun_9: string
  heavy_bow_gun_10: string
  hunting_horn_1: string
  hunting_horn_2: string
  hunting_horn_3: string
  hunting_horn_4: string
  hunting_horn_5: string
  hunting_horn_6: string
  hunting_horn_7: string
  hunting_horn_8: string
  hunting_horn_9: string
  hunting_horn_10: string
  insect_glaive_1: string
  insect_glaive_2: string
  insect_glaive_3: string
  insect_glaive_4: string
  insect_glaive_5: string
  insect_glaive_6: string
  insect_glaive_7: string
  insect_glaive_8: string
  insect_glaive_9: string
  insect_glaive_10: string
  lance_1: string
  lance_2: string
  lance_3: string
  lance_4: string
  lance_5: string
  lance_6: string
  lance_7: string
  lance_8: string
  lance_9: string
  lance_10: string
  gunlance_1: string
  gunlance_2: string
  gunlance_3: string
  gunlance_4: string
  gunlance_5: string
  gunlance_6: string
  gunlance_7: string
  gunlance_8: string
  gunlance_9: string
  gunlance_10: string
  long_sword_1: string
  long_sword_2: string
  long_sword_3: string
  long_sword_4: string
  long_sword_5: string
  long_sword_6: string
  long_sword_7: string
  long_sword_8: string
  long_sword_9: string
  long_sword_10: string
  switch_axe_1: string
  switch_axe_2: string
  switch_axe_3: string
  switch_axe_4: string
  switch_axe_5: string
  switch_axe_6: string
  switch_axe_7: string
  switch_axe_8: string
  switch_axe_9: string
  switch_axe_10: string
  sword_and_shield_1: string
  sword_and_shield_2: string
  sword_and_shield_3: string
  sword_and_shield_4: string
  sword_and_shield_5: string
  sword_and_shield_6: string
  sword_and_shield_7: string
  sword_and_shield_8: string
  sword_and_shield_9: string
  sword_and_shield_10: string
}
